apiVersion: v1
kind: Pod
metadata:
  name: todo-app
  labels:
    name: todo-app
spec:
  containers:
  - name: todo-app
    image: sudipdas2001/todoapp
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
