--- # install the python3
- hosts: demo
  user: ansible
  become: yes
  connection: ssh 
  gather_facts: yes 
  tasks:
      - name: install python on ubuntu
        action: yum name=python3 state=installed